"""
Pydantic models for CyberSentinel Lite.

This module contains all the data models used throughout the application:
- RouteDecision: For adaptive routing decisions
- DocumentGrade: For corrective RAG document grading
- IncidentReport: For structured threat reports
- CyberState: For LangGraph workflow state management
"""

from typing import List, Annotated
from pydantic import BaseModel, Field
from langgraph.graph.message import add_messages


class RouteDecision(BaseModel):
    """
    Decision model for the adaptive router.
    
    Determines whether a query should be answered directly by LLM
    or go through the full RAG pipeline.
    """
    route: str = Field(
        description="Route decision: 'direct_llm' for simple queries, 'full_rag' for complex investigations"
    )
    reason: str = Field(
        description="Explanation for why this route was chosen"
    )
    query_type: str = Field(
        description="Type of input: 'ip', 'cve', or 'keyword'"
    )


class DocumentGrade(BaseModel):
    """
    Grade for a retrieved document in the corrective RAG pipeline.
    
    Determines if a document is relevant to the query or should be discarded.
    """
    score: str = Field(
        description="Grade: 'relevant', 'irrelevant', or 'stale'"
    )
    reason: str = Field(
        description="Explanation for why this grade was assigned"
    )


class IncidentReport(BaseModel):
    """
    Structured threat report generated by the responder agent.
    
    Contains comprehensive information about a security threat or vulnerability.
    """
    threat_id: str = Field(
        description="Unique identifier for the threat (e.g., CVE ID, IP address, or generated ID)"
    )
    timestamp: str = Field(
        description="ISO timestamp of when the report was generated"
    )
    query: str = Field(
        description="Original user query that triggered this report"
    )
    threat_type: str = Field(
        description="Type of threat: 'malicious_ip', 'vulnerability', or 'news_threat'"
    )
    severity: str = Field(
        description="Severity level: 'low', 'medium', 'high', or 'critical'"
    )
    summary: str = Field(
        description="Brief summary of the threat"
    )
    affected_systems: List[str] = Field(
        default_factory=list,
        description="List of affected systems or software"
    )
    cve_references: List[str] = Field(
        default_factory=list,
        description="List of related CVE IDs"
    )
    indicators: List[str] = Field(
        default_factory=list,
        description="List of IOCs: IPs, hashes, domains, etc."
    )
    mitigation_steps: List[str] = Field(
        default_factory=list,
        description="Recommended mitigation steps"
    )
    confidence_score: float = Field(
        ge=0.0,
        le=1.0,
        description="Confidence score from 0.0 to 1.0"
    )
    source_used: str = Field(
        description="Which API/tool was used to generate this report"
    )


class CyberState(BaseModel):
    """
    State schema for the LangGraph workflow.
    
    Maintains the state as it flows through different nodes in the agent pipeline.
    """
    query: str = Field(
        default="",
        description="User input query"
    )
    query_type: str = Field(
        default="",
        description="Type of query: 'ip', 'cve', or 'keyword'"
    )
    route: str = Field(
        default="",
        description="Route decision: 'direct_llm' or 'full_rag'"
    )
    retrieved_data: List[str] = Field(
        default_factory=list,
        description="Raw data retrieved from APIs"
    )
    retrieval_grade: str = Field(
        default="",
        description="Grade of retrieval: 'relevant' or 'irrelevant'"
    )
    past_incidents: List[str] = Field(
        default_factory=list,
        description="Similar past incidents from ChromaDB"
    )
    final_report: dict = Field(
        default_factory=dict,
        description="Final incident report as dictionary"
    )
    messages: Annotated[list, add_messages] = Field(
        default_factory=list,
        description="Conversation messages for LangGraph"
    )
